Implement Mayhem
mayhemheroes/stream-ciphers pull request #1
Opened 2023-04-25 00:28 UTC by nottirb

- Added a `Dockerfile` for fuzz testing
- Added `Mayhemfile(s)` for fuzz testing
- Added a `mayhem.yml` file for automatically running fuzz tests with Mayhem using the mcode action
- Wrote 3 fuzz harnesses

2023-04-26 22:31 UTC, xansec requested changes
Please make the requested changes.

2023-04-26 22:31 UTC, xansec commented on fuzz/fuzz_targets/rabbit.rs
> +use honggfuzz::fuzz;
Asking again for confirmation of fixed random numbers dependent on test case/seed.

2023-04-26 22:31 UTC, xansec commented on mayhem/hc-256.Mayhemfile
> +project: stream-ciphers
Please omit image name.

2023-04-26 22:31 UTC, xansec commented on mayhem/salsa20.Mayhemfile
> +project: stream-ciphers
Please omit image name.

2023-04-27 08:47 UTC, nottirb commented
I removed the image name from the Mayhemfiles, and replaced StdRng with Pcg64 to ensure that it generates the same random number on different builds/platforms.

2023-05-07 06:26 UTC, xansec approved these changes
LGTM!

2023-05-07 06:26 UTC, merged